### ISSUE TITLE
Lodash Debounce Breaks

### ISSUE THREAD

**Issue by maxsalven** [boblauer/MockDate#13]
When I have MockDate enabled, calls to lodash's `debounce` function never execute. Any ideas?

Thanks

**Comment by boblauer** [comment]
Debounce works by determining how much time has passed between executions by subtracting the current time from the previous execution time. MockDate sets the clock to a fixed date and time and that value never changes, so debounce never sees any time pass.

I don't see a way around this unfortunately.

**Comment by boblauer** [comment]
On second thought, there may be a solution.  I'm thinking something like `MockDate.start()` that allows the clock to start ticking.  Something like this:

```js
MockDate.set(new Date('01/01/2000'))
new Date(); // 2000-01-01T06:00:00.000Z
MockDate.start();
// ~2 seconds elapse
new Date(); // 2000-01-01T06:00:02.327Z
MockDate.stop(); // resets  back to what it was originally set at
new Date(); // 2000-01-01T06:00:00.000Z
```

The downside is that people need to remember to call `stop`, or else the rest of their tests could fail.  The upside is supporting anything that requires time to move forward but doesn't use `setTimeout/setInterval`, such as `debounce`.

Thoughts?

**Comment by gibatronic** [comment]
I'm having a similar issue, but since I'm using [rewire](https://github.com/jhnns/rewire) I'm able to overwrite globals that are inside a module:

```javascript
const rewiredModule = rewire('./wild-module');

// mock Date
MockDate.set('1988-02-04T00:00:00.000Z');

// overwrite the Date being used inside my wild-module with the mocked one
rewiredModule.__set__({
  Date: Date
});
```

So, it would actually be really nice if MockDate could give me a mocked Date object, instead of overwriting the one in the global scope, something like this:

```javascript
const rewiredModule = rewire('./wild-module');

// mock Date
const mockedDate = MockDate.getMockedDate();

// overwrite the Date being used inside my wild-module with the mocked one
rewiredModule.__set__({
  Date: mockedDate
});

// then along the test
mockedDate.set('1988-02-04T00:00:00.000Z');
```

So in this way, MockDate won't interfere in any other place using Date.
Does it make sense to you guys?

**Comment by boblauer** [comment]
I have no plans to modify this library to not overwrite the global `Date` object, as that is the fundamental purpose of this library.  However, I do believe you can achieve what you're after by doing:

```js
MockDate.set(new Date());
const mockedDate = Date;
MockDate.reset();
```

**Comment by gibatronic** [comment]
Indeed, that might be enough. Thanks!

**Comment by donovanhiland** [comment]
> On second thought, there may be a solution. I'm thinking something like `MockDate.start()` that allows the clock to start ticking. Something like this:
> 
> ```js
> MockDate.set(new Date('01/01/2000'))
> new Date(); // 2000-01-01T06:00:00.000Z
> MockDate.start();
> // ~2 seconds elapse
> new Date(); // 2000-01-01T06:00:02.327Z
> MockDate.stop(); // resets  back to what it was originally set at
> new Date(); // 2000-01-01T06:00:00.000Z
> ```

Did you decide against this? Running into an issue where an api like this would be useful.

**Comment by falkenhawk** [comment]
Related PR that got rejected: https://github.com/boblauer/MockDate/pull/48
