### ISSUE TITLE
New Date() always get same value

### ISSUE THREAD

**Issue by facetime88** [boblauer/MockDate#14]
I am using MockDate to synchronize a client device with server. The problem occurred when I am trying to get New Date() value in a loop event. The value always the same. When I disable the mock and back using native, the value I get is updated and works as expected.

**Comment by boblauer** [comment]
Setting "now" to a static date is the exact use case of this package.  It should only be used in tests, when you want to test that code behaves a certain way given a specific date/time.

This library should absolutely not be used in any production code at all.
