### ISSUE TITLE
Input date format is not specified

### ISSUE THREAD

**Issue by TomGB** [boblauer/MockDate#15]
It is unclear that this package should be used as `MockDate(MM/DD/YYYY)`

**Comment by boblauer** [comment]
Thanks for opening an issue. Pull requests welcome!

**Comment by TomGB** [comment]
Sure: https://github.com/boblauer/MockDate/pull/16

**Comment by luketherrien** [comment]
@boblauer this issue has been fixed by [#16](https://github.com/boblauer/MockDate/pull/16), right?

**Comment by boblauer** [comment]
Yes, more or less. `MockDate` doesn't take a specific input format, it simply passes whatever it gets through to the `Date` object.  So there was no code change, just a documentation update.

**Comment by luketherrien** [comment]
Thanks so much for the library. It's perfect for testing :+1:
