### ISSUE TITLE
Add additional method for timestamp support?

### ISSUE THREAD

**Issue by GitProdEnv** [boblauer/MockDate#20]
I would rather test with timestamps, such as MockDate.setTimestamp(0);

such that I can test the behavior after a certain amount of seconds, minutes, etc. again.
e.g.: MockDate.setTimestamp(60000).

It would be awesome to have this functionality.

**Comment by boblauer** [comment]
I don't plan on implementing that, as it's orthogonal to what this library tries to accomplish.

That said, this might be what you're looking for - https://sinonjs.org/releases/v1.17.6/fake-timers/
