### ISSUE TITLE
NodeJS 10+ TimeoutOverflowWarning on MockDate.set

### ISSUE THREAD

**Issue by josephschmitt** [boblauer/MockDate#24]
I was hoping to have a PR to give you with a fix instead of just opening an issue, but I've been bashing my head against a wall trying to track this one down. When I use MockDate.set() with NodeJS 10 and up, I get the following sample warning:

```
(node:63747) TimeoutOverflowWarning: 1560177835614 does not fit into a 32-bit signed integer.
```

I've tracked it down to this specific line in `set`: https://github.com/boblauer/MockDate/blob/master/src/mockdate.js#L76

If I comment that line out, I no longer get the warning. But what's _really_ weird is, if I set `now` to _any_ integer, I _still_ get the error. Only commenting out or setting to `null` seems to silence the error.

Would love to understand what exactly is triggering node to throw this error and understand it. My curiosity isn't letting this one go.

**Comment by boblauer** [comment]
Which specific version of Node are you using? Does `npm run test` fail as well?

**Comment by josephschmitt** [comment]
Any version of NodeJS 10.0.0 and up displays the warning, while below doesn't.

**Comment by josephschmitt** [comment]
I'm trying to narrow down the use case out of my app. Will post a sample project here if I get there.

**Comment by boblauer** [comment]
I can't reproduce with 10.9.0 on OSX.

**Comment by josephschmitt** [comment]
Ok, so I've done some more debugging, and the issue seems to happen in conjunction with using the github API client library. They use the current date in the API request, which is why I'm trying to mock it. Best I can tell, they're doing some math on the results of `Date.now()` and I think `MockDate` is returning a string instead of an integer, meaning the math turns into concatenation, leading to the overflow. I'll keep digging.
