### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by connorjburton** [boblauer/MockDate#28]
There is no change log associated with this project.

https://keepachangelog.com/en/1.0.0/

**Comment by beporter** [comment]
Seconded. Particularly when you're updating things in your package.json across major versions, it's super helpful to be able to check a package's CHANGELOG for breaks. Taken alone this might not seem like a big deal, but multiply that by a couple dozen dependencies and the time adds up quick.

Thanks for the package and for your ongoing maintenance efforts. 🙇

**Comment by boblauer** [comment]
There is one now, hopefully it's helpful.
