### ISSUE TITLE
2.0.4: Typescript definition has syntax error

### ISSUE THREAD

**Issue by stnwk** [boblauer/MockDate#31]
Hi :)

Version `2.0.4` is currently exposing syntactically incorrect types from this commit: https://github.com/boblauer/MockDate/commit/654910dae56b284cc149e0bf979ae53fa3bcbf4a

![image](https://user-images.githubusercontent.com/2981250/62452902-65494980-b771-11e9-9112-b7e79949f1a8.png)

It needs to be a `;` instead of a `,`

Thanks :)

**Comment by wachunga** [comment]
Confirmed. Seeing this also.

**Comment by nickforddesign** [comment]
`2.0.5` has a fixed declaration file
