### ISSUE TITLE
This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export

### ISSUE THREAD

**Issue by RezaRahmati** [boblauer/MockDate#32]
Getting the below error in typescript project

`import * as MockDate from 'mockdate';
`
`This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export`

and if I add below to `tsconfig`, there will be error on other imports such as `import * as Rollbar from 'rollbar'` 

```
{
  "compilerOptions": {
    "esModuleInterop": true
  }
}
```

**Comment by RezaRahmati** [comment]
@boblauer Hey Bob, you closed this because it's an invalid bug or it's resolved or ..

**Comment by boblauer** [comment]
I rewrote the project in TS, should work as existed now

**Comment by RezaRahmati** [comment]
@boblauer Thanks for comment
