### ISSUE TITLE
Incorrect results based on format of date string

### ISSUE THREAD

**Issue by jd20** [boblauer/MockDate#33]
I came across a strange issue when using MockDate with a `YYYY-MM-DD` format date, versus `MM/DD/YYYY`. The results I see don't even agree with the first example shown in the README, so perhaps a recent bug?

Here's what I get in the node CLI:

```javascript
> MockDate.set('2000-11-22')
> new Date().toString()
'Tue Nov 21 2000 16:00:00 GMT-0800 (Pacific Standard Time)'
> MockDate.set('11/22/2000')
> new Date().toString()
'Wed Nov 22 2000 00:00:00 GMT-0800 (Pacific Standard Time)'
```

I would expect that both of these should give the same result. I'm using node v12.6.0 on macOS, MockDate 2.0.3.

**Comment by boblauer** [comment]
This is expected behavior. Whatever you pass to `MockDate.set` gets passed directly to the `Date` constructor. From MDN:

> Note: Parsing of date strings with the Date constructor (and Date.parse(), which works the same way) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. **Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.**

**Comment by jd20** [comment]
Doesn't that mean the first example in the README is wrong, then? It's showing an ISO 8601 string passed to `MockDate.set()`, and then `new Date().toString()` returning a date in CST timezone. Should the example be updated to clarify this behavior?

**Comment by boblauer** [comment]
Updated, thanks.
