### ISSUE TITLE
Request: add support for deterministic `Date.prototype.toString()` based on passed `timezoneOffset`

### ISSUE THREAD

**Issue by vvanpo** [boblauer/MockDate#35]
@boblauer you've mentioned that you don't consider this to be the purpose of this library: https://github.com/boblauer/MockDate/issues/19#issuecomment-470286501

Does that mean you wouldn't entertain a pull request that implements something like:
```js
MockDate.set(null, -60)

console.log(new Date('2019-11-13T23:41:46Z'))
  // Wed Nov 14 2019 00:41:46 GMT+0100
```

The full timezone representation is optional [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString#Description), meaning we only need the GMT offset.

I'm proposing `.toString()` and all methods that implicitly rely on the local timezone (the list is fairly long: `getDate`, `getDay`, `getHours`, `setHours`, etc.) are mocked to use the passed offset *only* when such an offset is passed. Existing usages that do not pass `timezoneOffset` to `MockDate.set()` will continue to use the native implementations.

My motivation for this proposal is that `MockDate` is often used for deterministic snapshot testing (e.g. Jest's `expect(...).toMatchSnapshot()`, where dates are often displayed and modified based on the runtime's local timezone. This is a problem when your CI server runs on UTC time, while your development machine doesn't. And if many developers work in different timezones, snapshots will fail.

I'd be interested to attempt this, but I'm a bit put-off by having to write in ES5. Would it be okay if I added Babel as a `devDependency`?

**Comment by vvanpo** [comment]
Reading your comment a little closer, I agree with your opinion that the current usage of `set()` is confusing. It only affects the behaviour of `new Date()`, not `new Date('<value>')`, and as you said the timezone offset does not affect how this date is interpreted by any of its methods.

If we're talking about a major version bump, I'd like to propose a different API:
```js
import { set, reset } from 'mockdate'

set({
  now: '2019-11-13T23:41:46Z',
  timezone: '+01:00',  // Up for discussion, JavaScript's timezone offset behaviour can be slightly confusing.
})

console.log(new Date().getTimezoneOffset())
  // -60
console.log(new Date())
  // Wed Nov 14 2019 00:41:46 GMT+0100

reset()
```

As well as another way to accomplish the same, using a callback:
```js
import MockDate from 'mockdate'

const now = '2019-11-13T23:41:46Z'
const timezone = '+01:00'

MockDate({ now, timezone }, () => {
  console.log(new Date())
    // Wed Nov 14 2019 00:41:46 GMT+0100
})

console.log(new Date())
  // The native Date output

// Should wait for a callback's promise, if it returns one.
MockDate({ now, timezone }, async () => {
  await new Promise(setTimeout)
  console.log(new Date())
}).then(() => console.log(new Date())
    // <mocked Date output>
    // <native Date output>
```

**Comment by boblauer** [comment]
I don't forsee adding more time zone support in the future, as I really would like to remove it completely and do a major version bump, but just haven't gotten around to it.

To solve your initial problem (and I suspect most problems that `timezoneOffset` might be used to solve), you can set Node's default TZ using an environment variable. This could be done when running your tests both locally and on your CI server so that everyone is always in the same timezone when running tests.

https://stackoverflow.com/questions/8083410/how-can-i-set-the-default-timezone-in-node-js

**Comment by vvanpo** [comment]
I didn't know about Node's `TZ`, thank you.

That doesn't solve the problem for tests intended to run in-browser, though.

**Comment by vvanpo** [comment]
> I don't forsee adding more time zone support in the future

My request wasn't for you to add it, my question was if you would be willing to entertain a pull request with the addition, so I know whether to put in the effort.

**Comment by boblauer** [comment]
Sorry, I should have been more clear, I don't think timezones should be a concern for this library, and so I wouldn't want any more timezone functionality added to it, regardless of author.

**Comment by vvanpo** [comment]
OK, that answers it for me. Thank you.

**Comment by vvanpo** [comment]
Node's `TZ` appears undocumented, and is heavily discouraged for testing because V8 caches the value (https://github.com/nodejs/node/issues/3449#issuecomment-271295444), and doesn't always make use of it (https://github.com/nodejs/node/issues/3449#issuecomment-150062461).

So it sounds like I'll have to create a new library that can mock timezones.

**Comment by vvanpo** [comment]
@boblauer FYI, Node version 10 removes all support for using `TZ`: 
![node-tz-unsupported](https://user-images.githubusercontent.com/3506391/68893643-6d9f1200-06da-11ea-94df-906d2355e688.png)

**Comment by boblauer** [comment]
Thanks for the follow up, that's good to know.

Thinking more about your original problem, another solution might be to use `MockDate` but update `MockDate.prototype.toString` (or whatever method you're using to display the date to the end user) and instead have it return `date.getTime()`. That will return ticks, which is timezone-agnostic.

**Comment by vvanpo** [comment]
That's not a bad idea, for simple scenarios that don't also rely on `Date`'s various manipulation methods this would certainly be the simplest solution.

For context around why I brought this up: I'm currently trying to snapshot test a third-party component, to protect against breaking changes on package upgrade. This component makes use of several `Date` methods, like `setHours`. It uses `new Date().setHours(0, 0, 0, 0)` to determine the start of today's date, and changes it's markup based on this value. I've mocked these methods to get around this, but was looking for a more generic solution.
