### ISSUE TITLE
should add Moment to type definition

### ISSUE THREAD

**Issue by razbensimon** [boblauer/MockDate#36]
as in the docs, `set` can get  `Moment` object as input.
should update d.ts

**Comment by razbensimon** [comment]
why did you close it?

this is the code:
```typescript
export function set(date: string | number): void {
...
}
```

there is no Moment on the function declaration.

and the README says:

```javascript
MockDate.set(moment('3/30/2000')); // using momentjs
```

**Comment by boblauer** [comment]
Sorry I missed that. I just updated the documentation to be correct, which is `MockDate.set(moment().valueOf())`.
