### ISSUE TITLE
RFI: Any alternatives for mocking timezoneOffset?

### ISSUE THREAD

**Issue by MattyBalaam** [boblauer/MockDate#43]
I had been using the timezoneOffset in mockdate v2 to test some time/date utilities on a local machine and a server in a  different timezone. 

I have noticed you have removed this feature from the library which sounds fair enough, but I wondered if you had any pointers for users upgrading to 3 to use alternative approaches/libraries?

**Comment by doingweb** [comment]
Node honors the `TZ` environment variable, so you can use that to manipulate it.

One way to do it is to just add it to your test command (e.g. in `package.json`):

```
  "scripts": {
    "test": "TZ='UTC' jest",
  },
```

Another would be to [have it happen during global test setup](https://stackoverflow.com/a/56482581/467354). Either way, as long as its set up in time, `Date.prototype.getTimezoneOffset()` should return what you need.
