### ISSUE TITLE
Using MockDate with TypeORM breaks typeORM

### ISSUE THREAD

**Issue by yorickdevries** [boblauer/MockDate#44]
I use MockDate for testing of my routes. However, when I set a MockDate, the TypeORM library breaks and is not automatically parsing dates to date Objects anymore:

My test code without mockdate:
```ts
    const obj = new DBObject("name", new Date("2020-06-23T10:00Z"));
    await obj.save();
    await obj.reload();
    console.log(obj); // DBObject { name: 'name', publishDate: 2020-06-23T10:00:00.000Z, id: 1 }
```

If I set the MockDate, TypeORM is not able to parse the datefields from the database properly:
```ts
    mockDate.set(new Date());
    const obj = new DBObject("name", new Date("2020-06-23T10:00Z"));
    await obj.save();
    await obj.reload();
    console.log(obj); // DBObject { name: 'name', publishDate: 1592906400000, id: 1 }
```

So the MockDate implementation is not behaving like the Javascript Date object is ans I expect there is a bug in the MockDate implementation. Any idea what the reason could be?

For reference, this is my Object class using TypeORM.
```ts
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity } from "typeorm";

@Entity()
export default class DBObject extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  name: string;

  @Column()
  publishDate: Date;

  constructor(name: string, publishDate: Date) {
    super();
    this.name = name;
    this.publishDate = publishDate;
  }
}
```

**Comment by boblauer** [comment]
@yorickdevries Sorry I didn't see this sooner. Did you ever figure this out?

**Comment by yorickdevries** [comment]
No

**Comment by boblauer** [comment]
If you can provide a simple repo that reproduces this error, I'd be happy to look into it. I know nothing about `typeorm`, so off my head it's not clear to me what could be going wrong here. Closing for now.
