### ISSUE TITLE
Date.now not mocked

### ISSUE THREAD

**Issue by hatpick** [boblauer/MockDate#64]
Hello,

Date itself is mocked, but Date.now is still returning the current time. Any ideas?

```javascript
describe('My test', () => {
    beforeAll(() => {
      MockDate.set(1000);
    });
    afterAll(() => {
      MockDate.reset();
    });
    test('test 1', () => {      
      expect(Date.now()).toBe((new Date()).getTime());
    });
});
```

**Comment by boblauer** [comment]
Are you sure `Date.now()` is returning the current time, or is it possible that there's a 1ms difference between when `Date.now()` is called and `new Date().getTime()` is called, causing the assertion to fail?

**Comment by hatpick** [comment]
@boblauer I'm setting the mock date to 1000 ms which is 1 second after epoch. Date.now() returns real time which is much much bigger than 1000, it's easy to compare.
// After mock
Date.now() // returns real time big number
new Date()).getTime() // returns 1000, as expected

**Comment by boblauer** [comment]
Are you using some other time mocking library that could possibly be overwriting `Date.now` as well? What does `Date.now.toString()` give you?

**Comment by hatpick** [comment]
There is no competing mock for Date.now
```function now() { [native code] }```, it shows not mocked

**Comment by boblauer** [comment]
That's odd that it wouldn't be mocked, but `Date` itself is. You're not saving a reference to `now` and calling that, are you? In other words, you're calling `Date.now()` and not `var now = Date.now; now();`?

**Comment by hatpick** [comment]
directly, Date.now()

**Comment by boblauer** [comment]
What does `Date.toString()` give you?

**Comment by hatpick** [comment]
Date.toString is ```function Date() { [native code] }```

console.log(Date) is:
```
[Function: MockDate] {
      UTC: [Function: UTC],
      now: [Function (anonymous)],
      parse: [Function (anonymous)],
      toString: [Function (anonymous)]
    }
```

**Comment by boblauer** [comment]
I'm wondering if something like the following is happening (although obviously not exactly like this, but if somewhere the mock is being reset)

```
require('./lib/mockdate').set(1000)
var d = new Date()
require('./lib/mockdate').reset()
Date.now() // 1629512698885
d.valueOf() // 1000
```

**Comment by hatpick** [comment]
I'm pretty sure it's not the case, since only ```.now()``` call is not mocked.

**Comment by rfoel** [comment]
Had the same problem. I was using `now` while destructuring the `Date` object.
```js
// does not work
const { now } = Date
const now = Date.now
// works
const now = () => Date.now()
```
