### ISSUE TITLE
Date is mocked but timezone is not

### ISSUE THREAD

**Issue by ctsstc** [boblauer/MockDate#70]
I have a test where the ISO string representation of `new Date()` is displaying the following which includes my timezone.

```
2000-11-21T16:00:00.000-08:00
```

Our test is checking for:

```
2000-11-21T16:00:00.000-00:00
```

I've tried calling MockDate with these and had no luck.

```
MockDate.set('2000-11-22T00:00:00.000+00:00')
MockDate.set(new Date('2000-11-22T00:00:00.000+00:00'))
MockDate.set(new Date('2000-11-22T00:00:00.000Z'))
```

I'm creating the new date via `new Date()`
Which I would expect to return the same date that mockdate setup.
Maybe it is but I'm misunderstanding that my system's timezone is being taken into account when I'd prefer it not.
Maybe I need to mock my system's timezone as well?

I wonder if many of the other issues open are around the timezone?

**Comment by felipejoribeiro** [comment]
Same issue, is there any work around?

**Comment by alansamuel-tsv** [comment]
I ended up doing something like (i.e using dayjs / moment to convert to utc as thats the timezone i am using)
`mockdate.set(dayjs('2021-02-13').utc(true).toDate())`
