### ISSUE TITLE
enable time to pass, but start at a certain date?

### ISSUE THREAD

**Issue by elirov** [boblauer/MockDate#72]
Is there a way to mock the "start time" of the date, but let the date progress? This would be helpful in cases, where the component we're testing has a debounceTime() that needs to be accounted for, but we still want to start the test at a certain time.

**Comment by boblauer** [comment]
I just threw this together but from what I can tell it should work 🤞🏻 

```ts
import { set, reset } from "./mockdate";

export class MockTicker {
  private tickInterval: number;

  private intervalId?: number;

  public constructor(tickInterval = 100) {
    this.tickInterval = tickInterval;
  }

  start(date: Date) {
    const RealDate = Date;
    const realStart = RealDate.now();

    set(date);

    this.intervalId = setInterval(() => {
      const timePassed = RealDate.now() - realStart;
      set(date.getTime() + timePassed);
    }, this.tickInterval);
  }

  reset() {
    clearInterval(this.intervalId);
    reset();
  }
}
```

My quick test script was:

```ts
import { MockTicker } from "./mockticker";

const ticker = new MockTicker();

ticker.start(new Date("1/1/2000"));

setInterval(() => {
  console.log(new Date());
}, 500);
```

Let me know if it works!

**Comment by elirov** [comment]
That's fantastic. Thank you!

**Comment by elirov** [comment]
Slightly modified to start from a fixed point and count from there: (and don't really need to cleanup in my case)

import { set } from 'mockdate';

const fixedStartTime = 1728054739853;

const realNow = Date.now;
const realStart = Date.now();

set(fixedStartTime);

setInterval(() => {
  const timePassed = realNow() - realStart;
  set(fixedStartTime + timePassed);
}, 100);

**Comment by joshuakcockrell** [comment]
You can advance the time ahead 1 second with

`MockDate.set(Date.now() + 1000); // Delay 1s`
