### ISSUE TITLE
Doesn't work with mongoose

### ISSUE THREAD

**Issue by bojidar-bg** [boblauer/MockDate#8]
It makes mongoose throw `TypeError: Undefined type "MockDate" at "created"`, if it is loaded before schemas are created.

**Comment by boblauer** [comment]
Are you just requiring MockDate before the schemas are created, or are you actually calling MockDate.set before they're created?

**Comment by bojidar-bg** [comment]
I'm setting them before the schemas are loaded. I'm currently workarounding it by doing this after `.set`:
```
Object.defineProperty(Date, 'name', {
  value: 'Date'
});
```

**Comment by boblauer** [comment]
The true fix is going to be to not set a mock date until the schemas have all been created. There's no fix I can do on my end, MockDate works by overwriting the Date object, which mongoose doesn't like when creating the schemas.

**Comment by bojidar-bg** [comment]
@boblauer It doesn't like the constructor's name (your constructor is named MockDate, not just Date).

**Comment by boblauer** [comment]
In general, you shouldn't overwrite the Date object before creating your schemas. It could lead to unpredictable behavior.

**Comment by sibelius** [comment]
what about this fix https://github.com/alexandr2110pro/jest-date-mock-mongoose-friendly/commit/6b37822fa09d81ed896f74bb41198b0dfb9c4519?

does it make sense?

**Comment by sibelius** [comment]
@bojidar-bg where are you putting this fix?

**Comment by bojidar-bg** [comment]
@sibelius Honestly, I don't remember now; I don't work on the project which used this any more. :smiley:

**Comment by sibelius** [comment]
@boblauer would you accept a PR to fix this?
